import {Urbanist} from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({
  subsets: ['latin'],
  weight: ['400','500','600','700'],
  variable: '--font-sans',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`text-gray-900 bg-gray-50 ${urbanist.variable}`}>
        {children}
      </body>
    </html>
  );
}
