import {} from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-gray-900 font-sans bg-gray-50">
        {children}
      </body>
    </html>
  );
}
